#ifndef RADIO_PAGE_H
#define RADIO_PAGE_H

static const char RADIO_PAGE_HTML[] = 
"<!DOCTYPE html>"
"<html lang='pt-BR'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>Benedicta Tu • Web Rádio</title>"
"<style>"
":root {"
"  --bg: #FAF8F5;"
"  --card: #FFFFFF;"
"  --card-hover: #FCFBFA;"
"  --border: #E8E2D6;"
"  --border-active: #C59B27;"
"  --primary: #B88A1B;"
"  --primary-glow: rgba(184, 138, 27, 0.25);"
"  --accent: #1E3A8A;"
"  --success: #15803D;"
"  --danger: #DC2626;"
"  --text: #0F1933;"
"  --text-dim: #53647C;"
"  --radius: 18px;"
"}"
"* { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; }"
"html, body {"
"  width: 100%;"
"  max-width: 100vw;"
"  overflow-x: hidden;"
"}"
"body {"
"  background-color: var(--bg);"
"  background-image: radial-gradient(at 10% 10%, rgba(184, 138, 27, 0.08) 0px, transparent 50%),"
"                    radial-gradient(at 90% 90%, rgba(30, 58, 138, 0.05) 0px, transparent 50%);"
"  background-attachment: fixed;"
"  color: var(--text);"
"  min-height: 100vh;"
"  display: flex;"
"  flex-direction: column;"
"  align-items: center;"
"  padding: 24px 16px 40px;"
"}"
".header-bar {"
"  max-width: 720px;"
"  width: 100%;"
"  display: flex;"
"  justify-content: space-between;"
"  align-items: center;"
"  margin-bottom: 24px;"
"  flex-wrap: wrap;"
"  gap: 12px;"
"}"
".brand { display: flex; align-items: center; gap: 10px; }"
".brand-icon { font-size: 1.8rem; filter: drop-shadow(0 2px 6px rgba(184, 138, 27, 0.3)); }"
".brand-title { font-size: 1.35rem; font-weight: 800; letter-spacing: -0.02em; color: var(--text); }"
".brand-sub { font-size: 0.75rem; color: var(--primary); font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; }"
".header-actions { display: flex; align-items: center; gap: 10px; }"
".badge-pill {"
"  display: inline-flex;"
"  align-items: center;"
"  gap: 6px;"
"  padding: 6px 14px;"
"  background: #FFFFFF;"
"  border: 1px solid var(--border);"
"  border-radius: 99px;"
"  font-size: 0.8rem;"
"  color: var(--text-dim);"
"  box-shadow: 0 2px 6px rgba(15, 25, 51, 0.04);"
"}"
".badge-pill .dot { width: 8px; height: 8px; border-radius: 50%; background: var(--success); box-shadow: 0 0 6px var(--success); }"
".btn-wifi {"
"  display: inline-flex;"
"  align-items: center;"
"  gap: 6px;"
"  padding: 7px 14px;"
"  background: #FFFFFF;"
"  border: 1px solid var(--border);"
"  color: var(--text);"
"  border-radius: 99px;"
"  font-size: 0.8rem;"
"  font-weight: 600;"
"  text-decoration: none;"
"  box-shadow: 0 2px 6px rgba(15, 25, 51, 0.04);"
"  transition: all 0.2s;"
"}"
".btn-wifi:hover { background: #F8FAFC; color: var(--primary); border-color: var(--primary); }"
".player-card {"
"  max-width: 720px;"
"  width: 100%;"
"  background: var(--card);"
"  border: 1px solid var(--border);"
"  border-radius: var(--radius);"
"  box-shadow: 0 10px 30px rgba(15, 25, 51, 0.07), inset 0 1px 0 rgba(255,255,255,0.9);"
"  padding: 32px 28px;"
"  margin-bottom: 28px;"
"  text-align: center;"
"  position: relative;"
"  overflow: hidden;"
"}"
".player-card::before {"
"  content: '';"
"  position: absolute;"
"  top: 0; left: 0; right: 0; height: 4px;"
"  background: linear-gradient(90deg, #B88A1B, #1E3A8A, #15803D);"
"}"
".visualizer {"
"  display: flex;"
"  align-items: center;"
"  justify-content: center;"
"  gap: 5px;"
"  height: 36px;"
"  margin-bottom: 16px;"
"}"
".vbar {"
"  width: 4px;"
"  height: 8px;"
"  background: var(--primary);"
"  border-radius: 4px;"
"  transition: height 0.2s;"
"}"
".playing .vbar:nth-child(1) { animation: bounce 0.8s ease-in-out infinite 0.1s; }"
".playing .vbar:nth-child(2) { animation: bounce 0.9s ease-in-out infinite 0.3s; }"
".playing .vbar:nth-child(3) { animation: bounce 0.7s ease-in-out infinite 0.0s; }"
".playing .vbar:nth-child(4) { animation: bounce 1.1s ease-in-out infinite 0.4s; }"
".playing .vbar:nth-child(5) { animation: bounce 0.85s ease-in-out infinite 0.2s; }"
".playing .vbar:nth-child(6) { animation: bounce 0.75s ease-in-out infinite 0.5s; }"
"@keyframes bounce { 0%, 100% { height: 6px; } 50% { height: 32px; background: var(--accent); } }"
".station-title { font-size: 1.6rem; font-weight: 800; color: var(--text); margin-bottom: 6px; letter-spacing: -0.01em; }"
".station-url { font-size: 0.82rem; color: var(--text-dim); max-width: 500px; margin: 0 auto 16px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }"
".metrics-row {"
"  display: flex;"
"  justify-content: center;"
"  gap: 8px;"
"  flex-wrap: wrap;"
"  margin-bottom: 24px;"
"}"
".metric-badge {"
"  background: #F1F5F9;"
"  border: 1px solid #E2E8F0;"
"  padding: 4px 10px;"
"  border-radius: 6px;"
"  font-size: 0.75rem;"
"  color: #334155;"
"  font-weight: 600;"
"}"
".controls-row {"
"  display: flex;"
"  align-items: center;"
"  justify-content: center;"
"  gap: 20px;"
"  margin-bottom: 24px;"
"}"
".play-btn {"
"  width: 68px;"
"  height: 68px;"
"  border-radius: 50%;"
"  border: none;"
"  background: linear-gradient(135deg, #D4AF37, #B88A1B);"
"  color: #FFFFFF;"
"  font-size: 1.8rem;"
"  display: flex;"
"  align-items: center;"
"  justify-content: center;"
"  cursor: pointer;"
"  box-shadow: 0 4px 20px var(--primary-glow);"
"  transition: all 0.2s ease;"
"}"
".play-btn:hover { transform: scale(1.06); box-shadow: 0 6px 26px rgba(184, 138, 27, 0.45); }"
".play-btn:active { transform: scale(0.96); }"
".vol-container {"
"  max-width: 360px;"
"  margin: 0 auto;"
"  display: flex;"
"  align-items: center;"
"  gap: 12px;"
"  background: #F8FAFC;"
"  padding: 8px 16px;"
"  border-radius: 99px;"
"  border: 1px solid var(--border);"
"}"
".vol-icon { font-size: 1.1rem; color: var(--text-dim); }"
".vol-slider {"
"  flex: 1;"
"  -webkit-appearance: none;"
"  appearance: none;"
"  height: 6px;"
"  background: #E2E8F0;"
"  border-radius: 3px;"
"  outline: none;"
"}"
".vol-slider::-webkit-slider-thumb {"
"  -webkit-appearance: none;"
"  width: 18px;"
"  height: 18px;"
"  border-radius: 50%;"
"  background: var(--primary);"
"  box-shadow: 0 2px 6px rgba(184, 138, 27, 0.4);"
"  cursor: pointer;"
"  transition: transform 0.1s;"
"}"
".vol-slider::-webkit-slider-thumb:hover { transform: scale(1.2); }"
".vol-text { font-size: 0.8rem; font-weight: 700; width: 36px; text-align: right; color: var(--primary); }"
".section-header {"
"  max-width: 720px;"
"  width: 100%;"
"  display: flex;"
"  justify-content: space-between;"
"  align-items: center;"
"  margin-bottom: 14px;"
"}"
".section-title { font-size: 1.15rem; font-weight: 700; color: var(--text); display: flex; align-items: center; gap: 8px; }"
".btn-add {"
"  display: inline-flex;"
"  align-items: center;"
"  gap: 6px;"
"  background: #FEF9E7;"
"  border: 1px solid rgba(184, 138, 27, 0.35);"
"  color: var(--primary);"
"  padding: 6px 14px;"
"  border-radius: 99px;"
"  font-size: 0.82rem;"
"  font-weight: 700;"
"  cursor: pointer;"
"  transition: all 0.2s;"
"}"
".btn-add:hover { background: var(--primary); color: #FFFFFF; transform: translateY(-1px); }"
".stations-grid {"
"  max-width: 720px;"
"  width: 100%;"
"  display: grid;"
"  grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));"
"  gap: 14px;"
"  margin-bottom: 30px;"
"}"
".station-card {"
"  background: var(--card);"
"  border: 1px solid var(--border);"
"  border-radius: 14px;"
"  padding: 16px 18px;"
"  display: flex;"
"  align-items: center;"
"  justify-content: space-between;"
"  gap: 12px;"
"  transition: all 0.2s ease;"
"  cursor: pointer;"
"  min-width: 0;"
"  max-width: 100%;"
"  box-sizing: border-box;"
"  box-shadow: 0 2px 8px rgba(15, 25, 51, 0.04);"
"}"
".station-card:hover {"
"  background: var(--card-hover);"
"  border-color: var(--border-active);"
"  transform: translateY(-2px);"
"  box-shadow: 0 6px 18px rgba(184, 138, 27, 0.12);"
"}"
".station-card.active {"
"  border-color: var(--primary);"
"  background: #FFFDF8;"
"  box-shadow: 0 6px 20px rgba(184, 138, 27, 0.18);"
"}"
".station-card.tuning {"
"  border-color: var(--accent);"
"  background: #F8FAFC;"
"  box-shadow: 0 0 16px rgba(30, 58, 138, 0.2);"
"}"
".station-info { flex: 1; min-width: 0; overflow: hidden; }"
".card-name { font-size: 0.98rem; font-weight: 700; color: var(--text); margin-bottom: 3px; display: flex; align-items: center; gap: 8px; min-width: 0; overflow: hidden; }"
".card-title-text { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; flex: 1; min-width: 0; }"
".card-url { font-size: 0.76rem; color: var(--text-dim); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }"
".card-url.tuning { font-style: italic; color: var(--primary); }"
".mini-eq {"
"  display: inline-flex;"
"  align-items: flex-end;"
"  gap: 2px;"
"  height: 14px;"
"  width: 18px;"
"  flex-shrink: 0;"
"  padding-bottom: 1px;"
"}"
".mini-eq span {"
"  width: 3px;"
"  border-radius: 2px;"
"  display: inline-block;"
"}"
".mini-eq.tuning span {"
"  background: var(--primary);"
"  box-shadow: 0 0 6px var(--primary-glow);"
"  animation: miniEqTuning 0.5s ease-in-out infinite alternate;"
"}"
".mini-eq.tuning span:nth-child(1) { height: 40%; animation-delay: 0.0s; }"
".mini-eq.tuning span:nth-child(2) { height: 95%; animation-delay: 0.15s; }"
".mini-eq.tuning span:nth-child(3) { height: 60%; animation-delay: 0.3s; }"
".mini-eq.tuning span:nth-child(4) { height: 80%; animation-delay: 0.1s; }"
".mini-eq.playing span {"
"  background: var(--success);"
"  box-shadow: 0 0 6px rgba(21, 128, 61, 0.4);"
"  animation: miniEqPlaying 0.75s ease-in-out infinite alternate;"
"}"
".mini-eq.playing span:nth-child(1) { height: 35%; animation-delay: 0.1s; }"
".mini-eq.playing span:nth-child(2) { height: 100%; animation-delay: 0.3s; }"
".mini-eq.playing span:nth-child(3) { height: 55%; animation-delay: 0.05s; }"
".mini-eq.playing span:nth-child(4) { height: 75%; animation-delay: 0.25s; }"
"@keyframes miniEqTuning {"
"  0% { height: 25%; opacity: 0.4; }"
"  100% { height: 100%; opacity: 1; }"
"}"
"@keyframes miniEqPlaying {"
"  0% { height: 20%; }"
"  100% { height: 100%; }"
"}"
".card-actions { display: flex; align-items: center; gap: 8px; flex-shrink: 0; }"
".btn-card-del {"
"  background: none;"
"  border: none;"
"  color: #94A3B8;"
"  cursor: pointer;"
"  font-size: 1rem;"
"  padding: 6px;"
"  border-radius: 6px;"
"  transition: all 0.2s;"
"}"
".btn-card-del:hover { color: var(--danger); background: #FEE2E2; }"
".badge-playing-tag {"
"  font-size: 0.72rem;"
"  font-weight: 700;"
"  color: var(--success);"
"  background: #ECFDF5;"
"  border: 1px solid #A7F3D0;"
"  padding: 4px 8px;"
"  border-radius: 6px;"
"  letter-spacing: 0.04em;"
"  white-space: nowrap;"
"  flex-shrink: 0;"
"}"
".btn-catalog {"
"  background: linear-gradient(135deg, #B88A1B, #9E7412);"
"  color: #FFFFFF;"
"  border: 1px solid #B88A1B;"
"  box-shadow: 0 2px 8px rgba(184, 138, 27, 0.25);"
"}"
".btn-catalog:hover {"
"  background: #9E7412;"
"  color: #FFFFFF;"
"}"
".catalog-embed-box {"
"  background: #FFFFFF;"
"  border: 1px solid var(--border-active);"
"  border-radius: 18px;"
"  padding: 12px;"
"  box-shadow: 0 8px 30px rgba(15, 25, 51, 0.08);"
"}"
".catalog-url-bar {"
"  display: flex;"
"  gap: 8px;"
"  margin-bottom: 10px;"
"  align-items: center;"
"}"
".catalog-url-input {"
"  flex: 1;"
"  min-width: 0;"
"  padding: 8px 12px;"
"  border-radius: 8px;"
"  background: #F8FAFC;"
"  color: var(--text);"
"  border: 1px solid #CBD5E1;"
"  font-size: 12px;"
"}"
".catalog-btn-reload {"
"  padding: 8px 14px;"
"  border-radius: 8px;"
"  background: var(--primary);"
"  color: #FFFFFF;"
"  border: none;"
"  font-size: 12px;"
"  cursor: pointer;"
"  font-weight: 600;"
"  flex-shrink: 0;"
"  transition: background 0.2s;"
"}"
".catalog-btn-reload:hover {"
"  background: #9E7412;"
"}"
".catalog-iframe-view {"
"  width: 100%;"
"  height: 580px;"
"  border: none;"
"  border-radius: 12px;"
"  background: #FFFFFF;"
"  display: block;"
"}"
"@media (max-width: 600px) {"
"  body {"
"    padding: 14px 10px 32px;"
"  }"
"  .header-bar {"
"    margin-bottom: 16px;"
"    gap: 10px;"
"  }"
"  .brand-title {"
"    font-size: 1.15rem;"
"  }"
"  .brand-icon {"
"    font-size: 1.5rem;"
"  }"
"  .player-card {"
"    padding: 18px 12px;"
"    margin-bottom: 18px;"
"    border-radius: 14px;"
"  }"
"  .station-title {"
"    font-size: 1.25rem;"
"    margin-bottom: 4px;"
"  }"
"  .station-url {"
"    font-size: 0.72rem;"
"    margin-bottom: 12px;"
"  }"
"  .metrics-row {"
"    gap: 6px;"
"    margin-bottom: 16px;"
"  }"
"  .metric-badge {"
"    font-size: 0.68rem;"
"    padding: 3px 8px;"
"  }"
"  .controls-row {"
"    margin-bottom: 16px;"
"  }"
"  .play-btn {"
"    width: 60px;"
"    height: 60px;"
"    font-size: 1.5rem;"
"  }"
"  .vol-container {"
"    max-width: 100%;"
"    padding: 6px 12px;"
"  }"
"  .section-header {"
"    flex-direction: column;"
"    align-items: stretch;"
"    gap: 8px;"
"    margin-bottom: 12px;"
"  }"
"  .section-title {"
"    font-size: 1rem;"
"    justify-content: flex-start;"
"  }"
"  .btn-add {"
"    width: 100%;"
"    justify-content: center;"
"    padding: 9px 14px;"
"    font-size: 0.85rem;"
"  }"
"  .catalog-embed-box {"
"    padding: 8px 6px;"
"    border-radius: 12px;"
"  }"
"  .catalog-url-bar {"
"    gap: 6px;"
"    margin-bottom: 8px;"
"  }"
"  .catalog-url-input {"
"    font-size: 11px;"
"    padding: 7px 10px;"
"  }"
"  .catalog-btn-reload {"
"    font-size: 11px;"
"    padding: 7px 10px;"
"  }"
"  .catalog-iframe-view {"
"    height: 590px;"
"    border-radius: 8px;"
"  }"
"  .stations-grid {"
"    grid-template-columns: minmax(0, 1fr) !important;"
"    width: 100%;"
"    max-width: 100%;"
"    gap: 10px;"
"    margin-bottom: 24px;"
"    box-sizing: border-box;"
"  }"
"  .station-card {"
"    padding: 12px 14px;"
"    border-radius: 12px;"
"    min-width: 0;"
"    max-width: 100%;"
"    box-sizing: border-box;"
"  }"
"  .badge-playing-tag {"
"    font-size: 0.68rem;"
"    padding: 3px 6px;"
"    flex-shrink: 0;"
"  }"
"}"
"</style>"
"</head>"
"<body>"
"<div class='header-bar'>"
"  <div class='brand'>"
"    <div class='brand-icon'>🕊️</div>"
"    <div>"
"      <div class='brand-title'>Benedicta Tu</div>"
"      <div class='brand-sub'>Rádio Católica no Lar</div>"
"    </div>"
"  </div>"
"  <div class='header-actions'>"
"    <div class='badge-pill' id='wifiPill'><span class='dot'></span> Conectado</div>"
"    <a href='/wifi' class='btn-wifi'>⚙️ Wi-Fi</a>"
"  </div>"
"</div>"
"<div class='player-card' id='playerCard'>"
"  <div class='visualizer' id='visualizer'>"
"    <div class='vbar'></div><div class='vbar'></div><div class='vbar'></div>"
"    <div class='vbar'></div><div class='vbar'></div><div class='vbar'></div>"
"  </div>"
"  <div class='station-title' id='currentStationName'>Carregando estação...</div>"
"  <div class='station-url' id='currentStationUrl'>-</div>"
"  <div class='metrics-row'>"
"    <div class='metric-badge' id='statusPlaying'>Carregando...</div>"
"    <div class='metric-badge' id='statusFormat'>MP3 Estéreo</div>"
"    <div class='metric-badge' id='statusHz'>44.1 kHz</div>"
"    <div class='metric-badge' id='statusBitrate'>128 kbps</div>"
"    <div class='metric-badge' id='statusBuffer'>Buffer: 0 KB</div>"
"  </div>"
"  <div class='controls-row'>"
"    <button class='play-btn' id='playBtn' onclick='togglePlay()' title='Play/Pause'>▶</button>"
"  </div>"
"  <div class='vol-container'>"
"    <span class='vol-icon'>🔉</span>"
"    <input type='range' class='vol-slider' id='volSlider' min='0' max='100' value='60' oninput='onVolumeChange(this.value)'>"
"    <span class='vol-text' id='volText'>60%</span>"
"  </div>"
"</div>"
"<div class='section-header'>"
"  <div class='section-title'><span style='color:#f59e0b;'>✟</span> Catálogo Benedicta Tu (Local)</div>"
"  <button class='btn-add btn-catalog' onclick='toggleCatalog()'>🕊️ Explorar Catálogo</button>"
"</div>"
"<div id='catalogContainer' style='max-width:720px; width:100%; display:none; margin-bottom:24px;'>"
"  <div class='catalog-embed-box'>"
"    <div class='catalog-url-bar'>"
"      <input type='text' class='catalog-url-input' id='catalogUrlInput' value='http://localhost:3000/embed/catalog'>"
"      <button class='catalog-btn-reload' onclick='updateCatalogUrl()'>Recarregar</button>"
"    </div>"
"    <iframe class='catalog-iframe-view' id='catalogIframe' src='http://localhost:3000/embed/catalog' onload='sendStationsToCatalog()'></iframe>"
"  </div>"
"</div>"
"<div class='section-header'>"
"  <div class='section-title'><span>📡</span> Estações de Rádio Salvas</div>"
"</div>"
"<div class='stations-grid' id='stationsGrid'>"
"  <!-- Cards injetados via JS -->"
"</div>"
"<script>"
"let s_isPlaying = false;"
"let s_currentUrl = '';"
"let s_currentName = '';"
"let s_stations = [];"
"let s_volDebounce = null;"
"let s_isTuning = false;"
"let s_tuningTimeout = null;"
"async function fetchStatus() {"
"  try {"
"    const res = await fetch('/api/status');"
"    if (!res.ok) return;"
"    const data = await res.json();"
"    s_isPlaying = data.playing;"
"    s_currentUrl = data.url || '';"
"    s_currentName = data.name || 'Web Radio';"
"    document.getElementById('currentStationName').innerText = s_currentName;"
"    document.getElementById('currentStationUrl').innerText = s_currentUrl;"
"    document.getElementById('statusPlaying').innerText = s_isPlaying ? 'AO VIVO' : 'PAUSADO';"
"    document.getElementById('statusPlaying').style.color = s_isPlaying ? 'var(--success)' : 'var(--text-dim)';"
"    if (s_isPlaying) {"
"      s_isTuning = false;"
"      if (s_tuningTimeout) { clearTimeout(s_tuningTimeout); s_tuningTimeout = null; }"
"    }"
"    document.getElementById('statusHz').innerText = (data.hz ? (data.hz / 1000).toFixed(1) + ' kHz' : '44.1 kHz');"
"    document.getElementById('statusBitrate').innerText = (data.bitrate ? data.bitrate + ' kbps' : '128 kbps');"
"    document.getElementById('statusBuffer').innerText = 'Buffer: ' + Math.round((data.buffer || 0) / 1024) + ' KB';"
"    const playBtn = document.getElementById('playBtn');"
"    const card = document.getElementById('playerCard');"
"    if (s_isPlaying) {"
"      playBtn.innerHTML = '❚❚';"
"      card.classList.add('playing');"
"    } else {"
"      playBtn.innerHTML = '▶';"
"      card.classList.remove('playing');"
"    }"
"    if (!s_volDebounce && data.volume !== undefined) {"
"      document.getElementById('volSlider').value = data.volume;"
"      document.getElementById('volText').innerText = data.volume + '%';"
"    }"
"    updateActiveCards();"
"  } catch(e) {}"
"}"
"async function fetchStations() {"
"  try {"
"    const res = await fetch('/api/stations');"
"    if (!res.ok) return;"
"    s_stations = await res.json();"
"    renderStations();"
"    sendStationsToCatalog();"
"  } catch(e) {}"
"}"
"function getEqHtml(isTuning, isPlaying) {"
"  if (isTuning) {"
"    return '<span class=\"mini-eq tuning\" title=\"Sintonizando...\"><span></span><span></span><span></span><span></span></span>';"
"  } else if (isPlaying) {"
"    return '<span class=\"mini-eq playing\" title=\"No Ar\"><span></span><span></span><span></span><span></span></span>';"
"  }"
"  return '';"
"}"
"function renderStations() {"
"  const grid = document.getElementById('stationsGrid');"
"  grid.innerHTML = '';"
"  s_stations.forEach(st => {"
"    const isCurrent = (st.url === s_currentUrl);"
"    const isPlayingThis = (isCurrent && s_isPlaying);"
"    const card = document.createElement('div');"
"    card.className = 'station-card' + (isCurrent ? (' active' + (s_isTuning ? ' tuning' : '')) : '');"
"    card.dataset.id = st.id;"
"    card.dataset.url = st.url;"
"    card.dataset.name = st.name;"
"    card.onclick = (e) => {"
"      if (e.target.closest('.btn-card-del')) return;"
"      if (s_isTuning) return;"
"      tuneStation(st.name, st.url);"
"    };"
"    const eq = isCurrent ? getEqHtml(s_isTuning, s_isPlaying) : '';"
"    const isTuningThis = (isCurrent && s_isTuning);"
"    const urlClass = 'card-url' + (isTuningThis ? ' tuning' : '');"
"    const urlText = isTuningThis ? 'Sintonizando estação...' : escapeHtml(st.url);"
"    const actionHtml = isPlayingThis"
"      ? '<span class=\"badge-playing-tag\" title=\"Rádio em reprodução (protegida contra exclusão)\">▶ NO AR</span>'"
"      : '<button class=\"btn-card-del\" title=\"Excluir rádio\" onclick=\"deleteStation(' + st.id + ', event)\">🗑️</button>';"
"    card.innerHTML = "
"      '<div class=\"station-info\">' +"
"        '<div class=\"card-name\">' +"
"          '<span class=\"card-title-text\">' + escapeHtml(st.name) + '</span>' + eq +"
"        '</div>' +"
"        '<div class=\"' + urlClass + '\">' + urlText + '</div>' +"
"      '</div>' +"
"      '<div class=\"card-actions\">' +"
"        + actionHtml +"
"      '</div>';"
"    grid.appendChild(card);"
"  });"
"}"
"function updateActiveCards() {"
"  const cards = document.querySelectorAll('.station-card');"
"  cards.forEach(c => {"
"    const isCurrent = (c.dataset.url === s_currentUrl);"
"    const nameDiv = c.querySelector('.card-name');"
"    const urlDiv = c.querySelector('.card-url');"
"    const actionsDiv = c.querySelector('.card-actions');"
"    const name = c.dataset.name || '';"
"    const url = c.dataset.url || '';"
"    const id = c.dataset.id || '';"
"    if (isCurrent) {"
"      c.className = 'station-card active' + (s_isTuning ? ' tuning' : '');"
"      if (nameDiv) {"
"        nameDiv.innerHTML = '<span class=\"card-title-text\">' + escapeHtml(name) + '</span>' + getEqHtml(s_isTuning, s_isPlaying);"
"      }"
"      if (actionsDiv) {"
"        if (s_isPlaying) {"
"          actionsDiv.innerHTML = '<span class=\"badge-playing-tag\" title=\"Rádio em reprodução (protegida contra exclusão)\">▶ NO AR</span>';"
"        } else if (id) {"
"          actionsDiv.innerHTML = '<button class=\"btn-card-del\" title=\"Excluir rádio\" onclick=\"deleteStation(' + id + ', event)\">🗑️</button>';"
"        }"
"      }"
"      if (urlDiv) {"
"        if (s_isTuning) {"
"          urlDiv.className = 'card-url tuning';"
"          urlDiv.innerText = 'Sintonizando estação...';"
"        } else {"
"          urlDiv.className = 'card-url';"
"          urlDiv.innerText = url;"
"        }"
"      }"
"    } else {"
"      c.className = 'station-card';"
"      if (nameDiv) {"
"        nameDiv.innerHTML = '<span class=\"card-title-text\">' + escapeHtml(name) + '</span>';"
"      }"
"      if (actionsDiv && id) {"
"        actionsDiv.innerHTML = '<button class=\"btn-card-del\" title=\"Excluir rádio\" onclick=\"deleteStation(' + id + ', event)\">🗑️</button>';"
"      }"
"      if (urlDiv) {"
"        urlDiv.className = 'card-url';"
"        urlDiv.innerText = url;"
"      }"
"    }"
"  });"
"}"
"async function tuneStation(name, url) {"
"  if (s_isTuning) return;"
"  s_isTuning = true;"
"  if (s_tuningTimeout) clearTimeout(s_tuningTimeout);"
"  s_tuningTimeout = setTimeout(() => {"
"    if (s_isTuning) {"
"      s_isTuning = false;"
"      updateActiveCards();"
"    }"
"  }, 10000);"
"  s_currentUrl = url;"
"  s_currentName = name;"
"  document.getElementById('currentStationName').innerText = name;"
"  document.getElementById('currentStationUrl').innerText = url;"
"  updateActiveCards();"
"  try {"
"    await fetch('/api/play', {"
"      method: 'POST',"
"      headers: { 'Content-Type': 'application/json' },"
"      body: JSON.stringify({ name: name, url: url })"
"    });"
"    setTimeout(fetchStatus, 600);"
"  } catch(e) {"
"    alert('Erro ao sintonizar estação!');"
"    s_isTuning = false;"
"    if (s_tuningTimeout) { clearTimeout(s_tuningTimeout); s_tuningTimeout = null; }"
"    updateActiveCards();"
"  }"
"}"
"async function togglePlay() {"
"  try {"
"    if (s_isPlaying) {"
"      await fetch('/api/stop', { method: 'POST' });"
"    } else {"
"      await fetch('/api/play', {"
"        method: 'POST',"
"        headers: { 'Content-Type': 'application/json' },"
"        body: JSON.stringify({ name: s_currentName, url: s_currentUrl })"
"      });"
"    }"
"    fetchStatus();"
"  } catch(e) {}"
"}"
"function onVolumeChange(val) {"
"  document.getElementById('volText').innerText = val + '%';"
"  if (s_volDebounce) clearTimeout(s_volDebounce);"
"  s_volDebounce = setTimeout(async () => {"
"    try {"
"      await fetch('/api/volume', {"
"        method: 'POST',"
"        headers: { 'Content-Type': 'application/json' },"
"        body: JSON.stringify({ volume: parseInt(val) })"
"      });"
"    } catch(e) {}"
"    s_volDebounce = null;"
"  }, 120);"
"}"

"async function deleteStation(id, event) {"
"  if (event) event.stopPropagation();"
"  const st = s_stations.find(s => s.id === id);"
"  if (st && st.url === s_currentUrl && s_isPlaying) {"
"    alert('Esta rádio está em reprodução no momento.\\n\\nPara removê-la, pause a transmissão primeiro.');"
"    return;"
"  }"
"  if (!confirm('Deseja realmente remover esta rádio?')) return;"
"  try {"
"    const res = await fetch('/api/stations?id=' + id, { method: 'DELETE' });"
"    if (res.ok) {"
"      fetchStations();"
"    } else if (res.status === 409) {"
"      alert('Não é possível excluir esta rádio pois ela está em reprodução no momento.');"
"      fetchStations();"
"      fetchStatus();"
"    } else {"
"      alert('Erro ao excluir rádio!');"
"    }"
"  } catch(e) { alert('Erro ao excluir rádio!'); }"
"}"
"function escapeHtml(str) {"
"  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\"/g, '&quot;');"
"}"
"function sendStationsToCatalog() {"
"  const iframe = document.getElementById('catalogIframe');"
"  if (iframe && iframe.contentWindow && Array.isArray(s_stations)) {"
"    iframe.contentWindow.postMessage({"
"      type: 'BENEDICTATU_CURRENT_STATIONS',"
"      stations: s_stations,"
"      playingUrl: s_currentUrl,"
"      isPlaying: s_isPlaying"
"    }, '*');"
"  }"
"}"
"function toggleCatalog() {"
"  const el = document.getElementById('catalogContainer');"
"  const isOpening = (el.style.display === 'none' || !el.style.display);"
"  el.style.display = isOpening ? 'block' : 'none';"
"  if (isOpening) {"
"    sendStationsToCatalog();"
"  }"
"}"
"function updateCatalogUrl() {"
"  const val = document.getElementById('catalogUrlInput').value;"
"  if (val) document.getElementById('catalogIframe').src = val;"
"}"
"window.addEventListener('message', function(event) {"
"  if (!event.data) return;"
"  if (event.data.type === 'BENEDICTATU_ADD_STATIONS' || event.data.type === 'BENEDICTATU_STATIONS_UPDATE') {"
"    const list = event.data.stations;"
"    if (Array.isArray(list) && list.length > 0) {"
"      fetch('/api/stations/batch', {"
"        method: 'POST',"
"        headers: { 'Content-Type': 'application/json' },"
"        body: JSON.stringify(list)"
"      })"
"      .then(res => res.json())"
"      .then(data => {"
"        const added = (data && data.added !== undefined) ? data.added : list.length;"
"        if (added > 0) {"
"          alert('🕊️ Benedicta Tu: ' + added + ' nova(s) rádio(s) adicionada(s) ao aparelho com sucesso!');"
"        } else {"
"          alert('🕊️ Todas as rádios selecionadas já estão presentes no aparelho.');"
"        }"
"        fetchStations();"
"        toggleCatalog();"
"      })"
"      .catch(err => {"
"        alert('Erro ao gravar rádios: ' + err);"
"      });"
"    }"
"  } else if (event.data.type === 'BENEDICTATU_REQUEST_CURRENT_STATIONS') {"
"    sendStationsToCatalog();"
"  }"
"});"
"window.addEventListener('load', () => {"
"  fetchStations();"
"  fetchStatus();"
"  setInterval(fetchStatus, 2000);"
"});"
"</script>"
"</body>"
"</html>";

#endif // RADIO_PAGE_H
