#ifndef RADIO_PAGE_H
#define RADIO_PAGE_H

static const char RADIO_PAGE_HTML[] = 
"<!DOCTYPE html>"
"<html lang='pt-BR'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>Web Radio ESP32 - Sintonia & Controle</title>"
"<style>"
":root {"
"  --bg: #090d16;"
"  --card: rgba(21, 29, 47, 0.75);"
"  --card-hover: rgba(28, 39, 64, 0.85);"
"  --border: rgba(56, 189, 248, 0.15);"
"  --border-active: #38bdf8;"
"  --primary: #38bdf8;"
"  --primary-glow: rgba(56, 189, 248, 0.35);"
"  --accent: #818cf8;"
"  --success: #10b981;"
"  --danger: #ef4444;"
"  --text: #f8fafc;"
"  --text-dim: #94a3b8;"
"  --radius: 18px;"
"}"
"* { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; }"
"body {"
"  background-color: var(--bg);"
"  background-image: radial-gradient(at 10% 10%, rgba(56, 189, 248, 0.12) 0px, transparent 50%),"
"                    radial-gradient(at 90% 90%, rgba(129, 140, 248, 0.12) 0px, transparent 50%),"
"                    radial-gradient(at 50% 50%, rgba(16, 185, 129, 0.05) 0px, transparent 50%);"
"  background-attachment: fixed;"
"  color: var(--text);"
"  min-height: 100vh;"
"  display: flex;"
"  flex-direction: column;"
"  align-items: center;"
"  padding: 24px 16px 40px;"
"}"
".header-bar {"
"  max-width: 720px;"
"  width: 100%;"
"  display: flex;"
"  justify-content: space-between;"
"  align-items: center;"
"  margin-bottom: 24px;"
"  flex-wrap: wrap;"
"  gap: 12px;"
"}"
".brand { display: flex; align-items: center; gap: 10px; }"
".brand-icon { font-size: 1.8rem; filter: drop-shadow(0 0 8px var(--primary-glow)); }"
".brand-title { font-size: 1.3rem; font-weight: 800; letter-spacing: -0.02em; color: #fff; }"
".brand-sub { font-size: 0.75rem; color: var(--primary); font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; }"
".header-actions { display: flex; align-items: center; gap: 10px; }"
".badge-pill {"
"  display: inline-flex;"
"  align-items: center;"
"  gap: 6px;"
"  padding: 6px 14px;"
"  background: rgba(15, 23, 42, 0.8);"
"  border: 1px solid var(--border);"
"  border-radius: 99px;"
"  font-size: 0.8rem;"
"  color: var(--text-dim);"
"  backdrop-filter: blur(8px);"
"}"
".badge-pill .dot { width: 8px; height: 8px; border-radius: 50%; background: var(--success); box-shadow: 0 0 8px var(--success); }"
".btn-wifi {"
"  display: inline-flex;"
"  align-items: center;"
"  gap: 6px;"
"  padding: 7px 14px;"
"  background: rgba(30, 41, 59, 0.8);"
"  border: 1px solid #334155;"
"  color: #cbd5e1;"
"  border-radius: 99px;"
"  font-size: 0.8rem;"
"  font-weight: 600;"
"  text-decoration: none;"
"  transition: all 0.2s;"
"}"
".btn-wifi:hover { background: #334155; color: #fff; border-color: var(--primary); }"
".player-card {"
"  max-width: 720px;"
"  width: 100%;"
"  background: var(--card);"
"  backdrop-filter: blur(16px);"
"  -webkit-backdrop-filter: blur(16px);"
"  border: 1px solid var(--border);"
"  border-radius: var(--radius);"
"  box-shadow: 0 24px 48px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.06);"
"  padding: 32px 28px;"
"  margin-bottom: 28px;"
"  text-align: center;"
"  position: relative;"
"  overflow: hidden;"
"}"
".player-card::before {"
"  content: '';"
"  position: absolute;"
"  top: 0; left: 0; right: 0; height: 3px;"
"  background: linear-gradient(90deg, var(--primary), var(--accent), var(--success));"
"}"
".visualizer {"
"  display: flex;"
"  align-items: center;"
"  justify-content: center;"
"  gap: 5px;"
"  height: 36px;"
"  margin-bottom: 16px;"
"}"
".vbar {"
"  width: 4px;"
"  height: 8px;"
"  background: var(--primary);"
"  border-radius: 4px;"
"  transition: height 0.2s;"
"}"
".playing .vbar:nth-child(1) { animation: bounce 0.8s ease-in-out infinite 0.1s; }"
".playing .vbar:nth-child(2) { animation: bounce 0.9s ease-in-out infinite 0.3s; }"
".playing .vbar:nth-child(3) { animation: bounce 0.7s ease-in-out infinite 0.0s; }"
".playing .vbar:nth-child(4) { animation: bounce 1.1s ease-in-out infinite 0.4s; }"
".playing .vbar:nth-child(5) { animation: bounce 0.85s ease-in-out infinite 0.2s; }"
".playing .vbar:nth-child(6) { animation: bounce 0.75s ease-in-out infinite 0.5s; }"
"@keyframes bounce { 0%, 100% { height: 6px; } 50% { height: 32px; background: var(--accent); } }"
".station-title { font-size: 1.6rem; font-weight: 800; color: #fff; margin-bottom: 6px; letter-spacing: -0.01em; }"
".station-url { font-size: 0.82rem; color: var(--text-dim); max-width: 500px; margin: 0 auto 16px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }"
".metrics-row {"
"  display: flex;"
"  justify-content: center;"
"  gap: 8px;"
"  flex-wrap: wrap;"
"  margin-bottom: 24px;"
"}"
".metric-badge {"
"  background: rgba(15, 23, 42, 0.7);"
"  border: 1px solid rgba(255,255,255,0.06);"
"  padding: 4px 10px;"
"  border-radius: 6px;"
"  font-size: 0.75rem;"
"  color: #cbd5e1;"
"  font-weight: 600;"
"}"
".controls-row {"
"  display: flex;"
"  align-items: center;"
"  justify-content: center;"
"  gap: 20px;"
"  margin-bottom: 24px;"
"}"
".play-btn {"
"  width: 68px;"
"  height: 68px;"
"  border-radius: 50%;"
"  border: none;"
"  background: linear-gradient(135deg, var(--primary), var(--accent));"
"  color: #090d16;"
"  font-size: 1.8rem;"
"  display: flex;"
"  align-items: center;"
"  justify-content: center;"
"  cursor: pointer;"
"  box-shadow: 0 0 24px var(--primary-glow);"
"  transition: all 0.2s ease;"
"}"
".play-btn:hover { transform: scale(1.06); box-shadow: 0 0 32px var(--primary-glow); }"
".play-btn:active { transform: scale(0.96); }"
".vol-container {"
"  max-width: 360px;"
"  margin: 0 auto;"
"  display: flex;"
"  align-items: center;"
"  gap: 12px;"
"  background: rgba(13, 19, 34, 0.6);"
"  padding: 8px 16px;"
"  border-radius: 99px;"
"  border: 1px solid var(--border);"
"}"
".vol-icon { font-size: 1.1rem; color: var(--text-dim); }"
".vol-slider {"
"  flex: 1;"
"  -webkit-appearance: none;"
"  appearance: none;"
"  height: 6px;"
"  background: #24324f;"
"  border-radius: 3px;"
"  outline: none;"
"}"
".vol-slider::-webkit-slider-thumb {"
"  -webkit-appearance: none;"
"  width: 18px;"
"  height: 18px;"
"  border-radius: 50%;"
"  background: var(--primary);"
"  box-shadow: 0 0 10px var(--primary);"
"  cursor: pointer;"
"  transition: transform 0.1s;"
"}"
".vol-slider::-webkit-slider-thumb:hover { transform: scale(1.2); }"
".vol-text { font-size: 0.8rem; font-weight: 700; width: 36px; text-align: right; color: var(--primary); }"
".section-header {"
"  max-width: 720px;"
"  width: 100%;"
"  display: flex;"
"  justify-content: space-between;"
"  align-items: center;"
"  margin-bottom: 14px;"
"}"
".section-title { font-size: 1.1rem; font-weight: 700; color: #e2e8f0; display: flex; align-items: center; gap: 8px; }"
".btn-add {"
"  display: inline-flex;"
"  align-items: center;"
"  gap: 6px;"
"  background: rgba(56, 189, 248, 0.12);"
"  border: 1px solid rgba(56, 189, 248, 0.3);"
"  color: var(--primary);"
"  padding: 6px 14px;"
"  border-radius: 99px;"
"  font-size: 0.82rem;"
"  font-weight: 700;"
"  cursor: pointer;"
"  transition: all 0.2s;"
"}"
".btn-add:hover { background: var(--primary); color: #090d16; transform: translateY(-1px); }"
".stations-grid {"
"  max-width: 720px;"
"  width: 100%;"
"  display: grid;"
"  grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));"
"  gap: 14px;"
"  margin-bottom: 30px;"
"}"
".station-card {"
"  background: var(--card);"
"  border: 1px solid var(--border);"
"  border-radius: 14px;"
"  padding: 16px 18px;"
"  display: flex;"
"  align-items: center;"
"  justify-content: space-between;"
"  gap: 12px;"
"  transition: all 0.2s ease;"
"  cursor: pointer;"
"}"
".station-card:hover {"
"  background: var(--card-hover);"
"  border-color: rgba(56, 189, 248, 0.4);"
"  transform: translateY(-2px);"
"}"
".station-card.active {"
"  border-color: var(--primary);"
"  background: rgba(28, 44, 75, 0.85);"
"  box-shadow: 0 8px 20px rgba(56, 189, 248, 0.15);"
"}"
".station-card.tuning {"
"  border-color: #38bdf8;"
"  background: rgba(14, 28, 55, 0.95);"
"  box-shadow: 0 0 16px rgba(56, 189, 248, 0.35);"
"}"
".station-info { flex: 1; overflow: hidden; }"
".card-name { font-size: 0.98rem; font-weight: 700; color: #fff; margin-bottom: 3px; display: flex; align-items: center; gap: 8px; min-width: 0; }"
".card-title-text { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; flex: 1; min-width: 0; }"
".card-url { font-size: 0.76rem; color: var(--text-dim); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }"
".card-url.tuning { font-style: italic; color: #38bdf8; }"
".mini-eq {"
"  display: inline-flex;"
"  align-items: flex-end;"
"  gap: 2px;"
"  height: 14px;"
"  width: 18px;"
"  flex-shrink: 0;"
"  padding-bottom: 1px;"
"}"
".mini-eq span {"
"  width: 3px;"
"  border-radius: 2px;"
"  display: inline-block;"
"}"
".mini-eq.tuning span {"
"  background: #38bdf8;"
"  box-shadow: 0 0 6px rgba(56, 189, 248, 0.6);"
"  animation: miniEqTuning 0.5s ease-in-out infinite alternate;"
"}"
".mini-eq.tuning span:nth-child(1) { height: 40%; animation-delay: 0.0s; }"
".mini-eq.tuning span:nth-child(2) { height: 95%; animation-delay: 0.15s; }"
".mini-eq.tuning span:nth-child(3) { height: 60%; animation-delay: 0.3s; }"
".mini-eq.tuning span:nth-child(4) { height: 80%; animation-delay: 0.1s; }"
".mini-eq.playing span {"
"  background: var(--success);"
"  box-shadow: 0 0 6px rgba(16, 185, 129, 0.5);"
"  animation: miniEqPlaying 0.75s ease-in-out infinite alternate;"
"}"
".mini-eq.playing span:nth-child(1) { height: 35%; animation-delay: 0.1s; }"
".mini-eq.playing span:nth-child(2) { height: 100%; animation-delay: 0.3s; }"
".mini-eq.playing span:nth-child(3) { height: 55%; animation-delay: 0.05s; }"
".mini-eq.playing span:nth-child(4) { height: 75%; animation-delay: 0.25s; }"
"@keyframes miniEqTuning {"
"  0% { height: 25%; opacity: 0.4; }"
"  100% { height: 100%; opacity: 1; }"
"}"
"@keyframes miniEqPlaying {"
"  0% { height: 20%; }"
"  100% { height: 100%; }"
"}"
".card-actions { display: flex; align-items: center; gap: 8px; }"
".btn-card-del {"
"  background: none;"
"  border: none;"
"  color: #64748b;"
"  cursor: pointer;"
"  font-size: 1rem;"
"  padding: 6px;"
"  border-radius: 6px;"
"  transition: color 0.2s;"
"}"
".btn-card-del:hover { color: var(--danger); background: rgba(239, 68, 68, 0.1); }"
".modal-overlay {"
"  display: none;"
"  position: fixed;"
"  top: 0; left: 0; right: 0; bottom: 0;"
"  background: rgba(0,0,0,0.75);"
"  backdrop-filter: blur(6px);"
"  z-index: 999;"
"  align-items: center;"
"  justify-content: center;"
"  padding: 16px;"
"}"
".modal {"
"  background: #151d2f;"
"  border: 1px solid var(--border);"
"  border-radius: var(--radius);"
"  max-width: 460px;"
"  width: 100%;"
"  padding: 28px;"
"  box-shadow: 0 24px 48px rgba(0,0,0,0.8);"
"  animation: popIn 0.25s ease-out;"
"}"
"@keyframes popIn { from { opacity: 0; transform: scale(0.95); } to { opacity: 1; transform: scale(1); } }"
".modal-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }"
".modal-title { font-size: 1.2rem; font-weight: 800; color: #fff; }"
".btn-close { background: none; border: none; font-size: 1.4rem; color: var(--text-dim); cursor: pointer; }"
".btn-close:hover { color: #fff; }"
".form-group { margin-bottom: 18px; text-align: left; }"
"label { display: block; font-size: 0.82rem; font-weight: 600; color: #cbd5e1; margin-bottom: 6px; }"
"input[type='text'] {"
"  width: 100%;"
"  background: #0d1322;"
"  border: 1px solid var(--border);"
"  border-radius: 10px;"
"  padding: 12px 14px;"
"  color: #fff;"
"  font-size: 0.95rem;"
"  outline: none;"
"  transition: border-color 0.2s;"
"}"
"input[type='text']:focus { border-color: var(--primary); }"
".modal-actions { display: flex; gap: 10px; margin-top: 24px; }"
".btn-cancel {"
"  flex: 1;"
"  padding: 12px;"
"  background: #1e293b;"
"  border: 1px solid #334155;"
"  color: #cbd5e1;"
"  border-radius: 8px;"
"  font-weight: 600;"
"  cursor: pointer;"
"}"
".btn-save {"
"  flex: 1;"
"  padding: 12px;"
"  background: linear-gradient(135deg, var(--primary), var(--accent));"
"  border: none;"
"  color: #090d16;"
"  border-radius: 8px;"
"  font-weight: 700;"
"  cursor: pointer;"
"}"
"</style>"
"</head>"
"<body>"
"<div class='header-bar'>"
"  <div class='brand'>"
"    <div class='brand-icon'>📻</div>"
"    <div>"
"      <div class='brand-title'>Web Radio ESP32</div>"
"      <div class='brand-sub'>ESP32-Audio-Kit ES8388</div>"
"    </div>"
"  </div>"
"  <div class='header-actions'>"
"    <div class='badge-pill' id='wifiPill'><span class='dot'></span> Conectado</div>"
"    <a href='/wifi' class='btn-wifi'>⚙️ Wi-Fi</a>"
"  </div>"
"</div>"
"<div class='player-card' id='playerCard'>"
"  <div class='visualizer' id='visualizer'>"
"    <div class='vbar'></div><div class='vbar'></div><div class='vbar'></div>"
"    <div class='vbar'></div><div class='vbar'></div><div class='vbar'></div>"
"  </div>"
"  <div class='station-title' id='currentStationName'>Carregando estação...</div>"
"  <div class='station-url' id='currentStationUrl'>-</div>"
"  <div class='metrics-row'>"
"    <div class='metric-badge' id='statusPlaying'>Carregando...</div>"
"    <div class='metric-badge' id='statusFormat'>MP3 Estéreo</div>"
"    <div class='metric-badge' id='statusHz'>44.1 kHz</div>"
"    <div class='metric-badge' id='statusBitrate'>128 kbps</div>"
"    <div class='metric-badge' id='statusBuffer'>Buffer: 0 KB</div>"
"  </div>"
"  <div class='controls-row'>"
"    <button class='play-btn' id='playBtn' onclick='togglePlay()' title='Play/Pause'>▶</button>"
"  </div>"
"  <div class='vol-container'>"
"    <span class='vol-icon'>🔉</span>"
"    <input type='range' class='vol-slider' id='volSlider' min='0' max='100' value='60' oninput='onVolumeChange(this.value)'>"
"    <span class='vol-text' id='volText'>60%</span>"
"  </div>"
"</div>"
"<div class='section-header' style='margin-bottom:12px;'>"
"  <div class='section-title'><span style='color:#f59e0b;'>✟</span> Catálogo Benedicta Tu (Nuvem)</div>"
"  <button class='btn-add' style='background:linear-gradient(135deg, #c59b27, #eab308); color:#fff; border-color:#d97706;' onclick='toggleCatalog()'>🕊️ Explorar Catálogo</button>"
"</div>"
"<div id='catalogContainer' style='max-width:720px; width:100%; display:none; margin-bottom:24px;'>"
"  <div style='background:rgba(21, 29, 47, 0.95); border:1px solid rgba(197, 155, 39, 0.4); border-radius:18px; padding:12px; box-shadow:0 8px 32px rgba(0,0,0,0.5);'>"
"    <iframe id='catalogIframe' src='https://benedictatu.oficinabr.com/embed/catalog' style='width:100%; height:540px; border:none; border-radius:12px; background:#fff;'></iframe>"
"  </div>"
"</div>"
"<div class='section-header'>"
"  <div class='section-title'><span>📡</span> Estações de Rádio Salvas</div>"
"  <button class='btn-add' onclick='openAddModal()'>+ Adicionar Manual</button>"
"</div>"
"<div class='stations-grid' id='stationsGrid'>"
"  <!-- Cards injetados via JS -->"
"</div>"
"<!-- Modal Adicionar Rádio -->"
"<div class='modal-overlay' id='modalOverlay'>"
"  <div class='modal'>"
"    <div class='modal-header'>"
"      <div class='modal-title'>Cadastrar Nova Rádio</div>"
"      <button class='btn-close' onclick='closeAddModal()'>&times;</button>"
"    </div>"
"    <form onsubmit='submitNewStation(event)'>"
"      <div class='form-group'>"
"        <label for='newName'>Nome da Estação:</label>"
"        <input type='text' id='newName' placeholder='Ex: Antena 1, Jovem Pan...' required maxlength='60'>"
"      </div>"
"      <div class='form-group'>"
"        <label for='newUrl'>URL do Stream MP3:</label>"
"        <input type='text' id='newUrl' placeholder='http://exemplo.com/stream-mp3' required maxlength='250'>"
"      </div>"
"      <div class='modal-actions'>"
"        <button type='button' class='btn-cancel' onclick='closeAddModal()'>Cancelar</button>"
"        <button type='submit' class='btn-save' id='btnSaveStation'>Salvar Estação</button>"
"      </div>"
"    </form>"
"  </div>"
"</div>"
"<script>"
"let s_isPlaying = false;"
"let s_currentUrl = '';"
"let s_currentName = '';"
"let s_stations = [];"
"let s_volDebounce = null;"
"let s_isTuning = false;"
"let s_tuningTimeout = null;"
"async function fetchStatus() {"
"  try {"
"    const res = await fetch('/api/status');"
"    if (!res.ok) return;"
"    const data = await res.json();"
"    s_isPlaying = data.playing;"
"    s_currentUrl = data.url || '';"
"    s_currentName = data.name || 'Web Radio';"
"    document.getElementById('currentStationName').innerText = s_currentName;"
"    document.getElementById('currentStationUrl').innerText = s_currentUrl;"
"    document.getElementById('statusPlaying').innerText = s_isPlaying ? 'AO VIVO' : 'PAUSADO';"
"    document.getElementById('statusPlaying').style.color = s_isPlaying ? 'var(--success)' : 'var(--text-dim)';"
"    if (s_isPlaying) {"
"      s_isTuning = false;"
"      if (s_tuningTimeout) { clearTimeout(s_tuningTimeout); s_tuningTimeout = null; }"
"    }"
"    document.getElementById('statusHz').innerText = (data.hz ? (data.hz / 1000).toFixed(1) + ' kHz' : '44.1 kHz');"
"    document.getElementById('statusBitrate').innerText = (data.bitrate ? data.bitrate + ' kbps' : '128 kbps');"
"    document.getElementById('statusBuffer').innerText = 'Buffer: ' + Math.round((data.buffer || 0) / 1024) + ' KB';"
"    const playBtn = document.getElementById('playBtn');"
"    const card = document.getElementById('playerCard');"
"    if (s_isPlaying) {"
"      playBtn.innerHTML = '❚❚';"
"      card.classList.add('playing');"
"    } else {"
"      playBtn.innerHTML = '▶';"
"      card.classList.remove('playing');"
"    }"
"    if (!s_volDebounce && data.volume !== undefined) {"
"      document.getElementById('volSlider').value = data.volume;"
"      document.getElementById('volText').innerText = data.volume + '%';"
"    }"
"    updateActiveCards();"
"  } catch(e) {}"
"}"
"async function fetchStations() {"
"  try {"
"    const res = await fetch('/api/stations');"
"    if (!res.ok) return;"
"    s_stations = await res.json();"
"    renderStations();"
"  } catch(e) {}"
"}"
"function getEqHtml(isTuning, isPlaying) {"
"  if (isTuning) {"
"    return '<span class=\"mini-eq tuning\" title=\"Sintonizando...\"><span></span><span></span><span></span><span></span></span>';"
"  } else if (isPlaying) {"
"    return '<span class=\"mini-eq playing\" title=\"No Ar\"><span></span><span></span><span></span><span></span></span>';"
"  }"
"  return '';"
"}"
"function renderStations() {"
"  const grid = document.getElementById('stationsGrid');"
"  grid.innerHTML = '';"
"  s_stations.forEach(st => {"
"    const isCurrent = (st.url === s_currentUrl);"
"    const card = document.createElement('div');"
"    card.className = 'station-card' + (isCurrent ? (' active' + (s_isTuning ? ' tuning' : '')) : '');"
"    card.dataset.url = st.url;"
"    card.dataset.name = st.name;"
"    card.onclick = (e) => {"
"      if (e.target.closest('.btn-card-del')) return;"
"      if (s_isTuning) return;"
"      tuneStation(st.name, st.url);"
"    };"
"    const eq = isCurrent ? getEqHtml(s_isTuning, s_isPlaying) : '';"
"    const isTuningThis = (isCurrent && s_isTuning);"
"    const urlClass = 'card-url' + (isTuningThis ? ' tuning' : '');"
"    const urlText = isTuningThis ? 'Sintonizando estação...' : escapeHtml(st.url);"
"    card.innerHTML = "
"      '<div class=\"station-info\">' +"
"        '<div class=\"card-name\">' +"
"          '<span class=\"card-title-text\">' + escapeHtml(st.name) + '</span>' + eq +"
"        '</div>' +"
"        '<div class=\"' + urlClass + '\">' + urlText + '</div>' +"
"      '</div>' +"
"      '<div class=\"card-actions\">' +"
"        '<button class=\"btn-card-del\" title=\"Excluir rádio\" onclick=\"deleteStation(' + st.id + ', event)\">🗑️</button>' +"
"      '</div>';"
"    grid.appendChild(card);"
"  });"
"}"
"function updateActiveCards() {"
"  const cards = document.querySelectorAll('.station-card');"
"  cards.forEach(c => {"
"    const isCurrent = (c.dataset.url === s_currentUrl);"
"    const nameDiv = c.querySelector('.card-name');"
"    const urlDiv = c.querySelector('.card-url');"
"    const name = c.dataset.name || '';"
"    const url = c.dataset.url || '';"
"    if (isCurrent) {"
"      c.className = 'station-card active' + (s_isTuning ? ' tuning' : '');"
"      if (nameDiv) {"
"        nameDiv.innerHTML = '<span class=\"card-title-text\">' + escapeHtml(name) + '</span>' + getEqHtml(s_isTuning, s_isPlaying);"
"      }"
"      if (urlDiv) {"
"        if (s_isTuning) {"
"          urlDiv.className = 'card-url tuning';"
"          urlDiv.innerText = 'Sintonizando estação...';"
"        } else {"
"          urlDiv.className = 'card-url';"
"          urlDiv.innerText = url;"
"        }"
"      }"
"    } else {"
"      c.className = 'station-card';"
"      if (nameDiv) {"
"        nameDiv.innerHTML = '<span class=\"card-title-text\">' + escapeHtml(name) + '</span>';"
"      }"
"      if (urlDiv) {"
"        urlDiv.className = 'card-url';"
"        urlDiv.innerText = url;"
"      }"
"    }"
"  });"
"}"
"async function tuneStation(name, url) {"
"  if (s_isTuning) return;"
"  s_isTuning = true;"
"  if (s_tuningTimeout) clearTimeout(s_tuningTimeout);"
"  s_tuningTimeout = setTimeout(() => {"
"    if (s_isTuning) {"
"      s_isTuning = false;"
"      updateActiveCards();"
"    }"
"  }, 10000);"
"  s_currentUrl = url;"
"  s_currentName = name;"
"  document.getElementById('currentStationName').innerText = name;"
"  document.getElementById('currentStationUrl').innerText = url;"
"  updateActiveCards();"
"  try {"
"    await fetch('/api/play', {"
"      method: 'POST',"
"      headers: { 'Content-Type': 'application/json' },"
"      body: JSON.stringify({ name: name, url: url })"
"    });"
"    setTimeout(fetchStatus, 600);"
"  } catch(e) {"
"    alert('Erro ao sintonizar estação!');"
"    s_isTuning = false;"
"    if (s_tuningTimeout) { clearTimeout(s_tuningTimeout); s_tuningTimeout = null; }"
"    updateActiveCards();"
"  }"
"}"
"async function togglePlay() {"
"  try {"
"    if (s_isPlaying) {"
"      await fetch('/api/stop', { method: 'POST' });"
"    } else {"
"      await fetch('/api/play', {"
"        method: 'POST',"
"        headers: { 'Content-Type': 'application/json' },"
"        body: JSON.stringify({ name: s_currentName, url: s_currentUrl })"
"      });"
"    }"
"    fetchStatus();"
"  } catch(e) {}"
"}"
"function onVolumeChange(val) {"
"  document.getElementById('volText').innerText = val + '%';"
"  if (s_volDebounce) clearTimeout(s_volDebounce);"
"  s_volDebounce = setTimeout(async () => {"
"    try {"
"      await fetch('/api/volume', {"
"        method: 'POST',"
"        headers: { 'Content-Type': 'application/json' },"
"        body: JSON.stringify({ volume: parseInt(val) })"
"      });"
"    } catch(e) {}"
"    s_volDebounce = null;"
"  }, 120);"
"}"
"function openAddModal() {"
"  document.getElementById('modalOverlay').style.display = 'flex';"
"  document.getElementById('newName').value = '';"
"  document.getElementById('newUrl').value = '';"
"  document.getElementById('newName').focus();"
"}"
"function closeAddModal() {"
"  document.getElementById('modalOverlay').style.display = 'none';"
"}"
"async function submitNewStation(e) {"
"  e.preventDefault();"
"  const name = document.getElementById('newName').value.trim();"
"  const url = document.getElementById('newUrl').value.trim();"
"  if (!name || !url) return;"
"  if (!url.startsWith('http://') && !url.startsWith('https://')) {"
"    alert('A URL deve começar com http:// ou https://');"
"    return;"
"  }"
"  const btn = document.getElementById('btnSaveStation');"
"  btn.disabled = true;"
"  btn.innerText = 'Salvando...';"
"  try {"
"    const res = await fetch('/api/stations', {"
"      method: 'POST',"
"      headers: { 'Content-Type': 'application/json' },"
"      body: JSON.stringify({ name, url })"
"    });"
"    if (res.ok) {"
"      closeAddModal();"
"      fetchStations();"
"    } else {"
"      alert('Falha ao salvar rádio (limite atingido ou dados inválidos)');"
"    }"
"  } catch(e) { alert('Erro de rede ao salvar!'); }"
"  finally { btn.disabled = false; btn.innerText = 'Salvar Estação'; }"
"}"
"async function deleteStation(id, event) {"
"  if (event) event.stopPropagation();"
"  if (!confirm('Deseja realmente remover esta rádio?')) return;"
"  try {"
"    const res = await fetch('/api/stations?id=' + id, { method: 'DELETE' });"
"    if (res.ok) fetchStations();"
"  } catch(e) { alert('Erro ao excluir rádio!'); }"
"}"
"function escapeHtml(str) {"
"  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\"/g, '&quot;');"
"}"
"function toggleCatalog() {"
"  const el = document.getElementById('catalogContainer');"
"  el.style.display = (el.style.display === 'none' || !el.style.display) ? 'block' : 'none';"
"}"
"window.addEventListener('message', function(event) {"
"  if (event.data && event.data.type === 'BENEDICTATU_STATIONS_UPDATE') {"
"    const list = event.data.stations;"
"    if (Array.isArray(list) && list.length > 0) {"
"      fetch('/api/stations/batch', {"
"        method: 'POST',"
"        headers: { 'Content-Type': 'application/json' },"
"        body: JSON.stringify(list)"
"      })"
"      .then(res => res.json())"
"      .then(data => {"
"        alert('🕊️ Benedicta Tu: ' + list.length + ' estações gravadas no aparelho com sucesso!');"
"        fetchStations();"
"        toggleCatalog();"
"      })"
"      .catch(err => {"
"        alert('Erro ao gravar rádios: ' + err);"
"      });"
"    }"
"  }"
"});"
"window.addEventListener('load', () => {"
"  fetchStations();"
"  fetchStatus();"
"  setInterval(fetchStatus, 2000);"
"});"
"</script>"
"</body>"
"</html>";

#endif // RADIO_PAGE_H
