#ifndef SETUP_PAGE_H
#define SETUP_PAGE_H

static const char SETUP_PAGE_HTML[] = 
"<!DOCTYPE html>"
"<html lang='pt-BR'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>Web Radio ESP32 - Configuração Wi-Fi</title>"
"<style>"
":root {"
"  --bg: #0b0f19;"
"  --card: #151d2f;"
"  --border: #24324f;"
"  --primary: #38bdf8;"
"  --primary-hover: #0ea5e9;"
"  --text: #f1f5f9;"
"  --text-dim: #94a3b8;"
"  --accent: #6366f1;"
"  --success: #10b981;"
"  --radius: 14px;"
"}"
"* { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; }"
"body {"
"  background-color: var(--bg);"
"  background-image: radial-gradient(at 0% 0%, rgba(56, 189, 248, 0.12) 0px, transparent 50%),"
"                    radial-gradient(at 100% 100%, rgba(99, 102, 241, 0.15) 0px, transparent 50%);"
"  color: var(--text);"
"  min-height: 100vh;"
"  display: flex;"
"  align-items: center;"
"  justify-content: center;"
"  padding: 20px;"
"}"
".container {"
"  background: var(--card);"
"  border: 1px solid var(--border);"
"  box-shadow: 0 20px 40px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.08);"
"  border-radius: var(--radius);"
"  max-width: 440px;"
"  width: 100%;"
"  padding: 32px 28px;"
"  animation: fadeIn 0.4s ease-out;"
"}"
"@keyframes fadeIn { from { opacity: 0; transform: translateY(12px); } to { opacity: 1; transform: translateY(0); } }"
".header {"
"  text-align: center;"
"  margin-bottom: 26px;"
"}"
".badge {"
"  display: inline-block;"
"  padding: 4px 12px;"
"  background: rgba(56, 189, 248, 0.12);"
"  color: var(--primary);"
"  font-size: 0.75rem;"
"  font-weight: 700;"
"  border-radius: 99px;"
"  text-transform: uppercase;"
"  letter-spacing: 0.05em;"
"  margin-bottom: 12px;"
"  border: 1px solid rgba(56, 189, 248, 0.25);"
"}"
"h1 { font-size: 1.5rem; font-weight: 800; color: #fff; margin-bottom: 6px; display: flex; align-items: center; justify-content: center; gap: 8px; }"
"p.desc { font-size: 0.88rem; color: var(--text-dim); line-height: 1.4; }"
".ip-badge { margin-top: 6px; font-size: 0.78rem; color: #64748b; }"
".form-group { margin-bottom: 20px; }"
"label { display: block; font-size: 0.85rem; font-weight: 600; margin-bottom: 8px; color: #cbd5e1; }"
".input-wrapper { position: relative; }"
"select, input[type='text'], input[type='password'] {"
"  width: 100%;"
"  background: #0d1322;"
"  border: 1px solid var(--border);"
"  border-radius: 10px;"
"  padding: 12px 14px;"
"  color: #fff;"
"  font-size: 0.95rem;"
"  outline: none;"
"  transition: border-color 0.2s, box-shadow 0.2s;"
"}"
"select:focus, input:focus {"
"  border-color: var(--primary);"
"  box-shadow: 0 0 0 3px rgba(56, 189, 248, 0.2);"
"}"
".scan-btn {"
"  display: flex;"
"  align-items: center;"
"  justify-content: center;"
"  gap: 6px;"
"  width: 100%;"
"  background: #1e293b;"
"  border: 1px solid #334155;"
"  color: #cbd5e1;"
"  padding: 10px;"
"  border-radius: 8px;"
"  font-size: 0.85rem;"
"  font-weight: 600;"
"  cursor: pointer;"
"  margin-bottom: 16px;"
"  transition: all 0.2s;"
"}"
".scan-btn:hover { background: #334155; color: #fff; }"
".toggle-pwd {"
"  position: absolute;"
"  right: 12px;"
"  top: 50%;"
"  transform: translateY(-50%);"
"  background: none;"
"  border: none;"
"  color: var(--text-dim);"
"  cursor: pointer;"
"  font-size: 0.8rem;"
"  padding: 4px 6px;"
"}"
".btn-submit {"
"  width: 100%;"
"  background: linear-gradient(135deg, var(--primary), var(--accent));"
"  border: none;"
"  color: #0b0f19;"
"  font-size: 1rem;"
"  font-weight: 700;"
"  padding: 14px;"
"  border-radius: 10px;"
"  cursor: pointer;"
"  box-shadow: 0 8px 20px rgba(56, 189, 248, 0.3);"
"  transition: all 0.2s;"
"}"
".btn-submit:hover { opacity: 0.92; transform: translateY(-1px); }"
".btn-submit:disabled { opacity: 0.5; cursor: not-allowed; transform: none; }"
"#statusBox {"
"  display: none;"
"  margin-top: 18px;"
"  padding: 12px;"
"  border-radius: 8px;"
"  font-size: 0.88rem;"
"  text-align: center;"
"  line-height: 1.4;"
"}"
".status-info { background: rgba(56, 189, 248, 0.1); border: 1px solid rgba(56, 189, 248, 0.3); color: var(--primary); }"
".status-success { background: rgba(16, 185, 129, 0.1); border: 1px solid rgba(16, 185, 129, 0.3); color: var(--success); }"
".btn-back { display: inline-flex; align-items: center; gap: 6px; color: var(--text-dim); text-decoration: none; font-size: 0.85rem; font-weight: 600; margin-bottom: 20px; padding: 7px 14px; border-radius: 99px; background: rgba(30, 41, 59, 0.6); border: 1px solid var(--border); transition: all 0.2s; }"
".btn-back:hover { color: #fff; background: #1e293b; border-color: var(--primary); transform: translateX(-3px); }"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"  <a href='/' class='btn-back'>← Voltar para a Sintonia</a>"
"  <div class='header'>"
"    <div class='badge'>Setup Inicial</div>"
"    <h1>📻 Web Radio ESP32</h1>"
"    <p class='desc'>Configure a rede Wi-Fi para conectar sua Web Radio à internet.</p>"
"    <div class='ip-badge'>Portal: 10.10.10.1</div>"
"  </div>"
"  <button type='button' class='scan-btn' id='scanBtn' onclick='scanNetworks()'>"
"    <span id='scanIcon'>🔄</span> Buscar Redes Wi-Fi Próximas"
"  </button>"
"  <form id='wifiForm' onsubmit='saveCredentials(event)'>"
"    <div class='form-group' id='selectGroup'>"
"      <label for='ssidSelect'>Nome da Rede (SSID):</label>"
"      <select id='ssidSelect' onchange='handleSelectChange()'>"
"        <option value=''>Clique em 'Buscar Redes' acima...</option>"
"      </select>"
"      <button type='button' class='manual-toggle' onclick='toggleManualInput()'>Digitar nome da rede manualmente</button>"
"    </div>"
"    <div class='form-group' id='manualGroup' style='display: none;'>"
"      <label for='ssidManual'>Nome da Rede (Manual):</label>"
"      <input type='text' id='ssidManual' placeholder='Ex: MinhaCasa_2.4G'>"
"      <button type='button' class='manual-toggle' onclick='toggleManualInput()'>Voltar para lista de redes</button>"
"    </div>"
"    <div class='form-group'>"
"      <label for='password'>Senha da Rede:</label>"
"      <div class='input-wrapper'>"
"        <input type='password' id='password' placeholder='Digite a senha do Wi-Fi' autocomplete='current-password'>"
"        <button type='button' class='toggle-pwd' onclick='togglePassword()'>👁️</button>"
"      </div>"
"    </div>"
"    <button type='submit' class='btn-submit' id='submitBtn'>Salvar e Conectar</button>"
"  </form>"
"  <div id='statusBox'></div>"
"</div>"
"<script>"
"let manualMode = false;"
"function toggleManualInput() {"
"  manualMode = !manualMode;"
"  document.getElementById('selectGroup').style.display = manualMode ? 'none' : 'block';"
"  document.getElementById('manualGroup').style.display = manualMode ? 'block' : 'none';"
"}"
"function togglePassword() {"
"  const p = document.getElementById('password');"
"  p.type = p.type === 'password' ? 'text' : 'password';"
"}"
"function handleSelectChange() {"
"  const val = document.getElementById('ssidSelect').value;"
"  if (val) document.getElementById('password').focus();"
"}"
"async function scanNetworks() {"
"  const btn = document.getElementById('scanBtn');"
"  const sel = document.getElementById('ssidSelect');"
"  btn.disabled = true;"
"  btn.innerHTML = '<span>⏳</span> Escaneando redes...';"
"  try {"
"    const res = await fetch('/api/scan');"
"    const networks = await res.json();"
"    sel.innerHTML = '<option value=\"\">Selecione uma rede...</option>';"
"    networks.forEach(n => {"
"      const opt = document.createElement('option');"
"      opt.value = n.ssid;"
"      opt.text = n.ssid + ' (' + n.rssi + ' dBm)' + (n.auth ? ' 🔒' : ' 🔓');"
"      sel.appendChild(opt);"
"    });"
"    if (manualMode) toggleManualInput();"
"  } catch (err) {"
"    alert('Erro ao buscar redes Wi-Fi. Tente novamente.');"
"  } finally {"
"    btn.disabled = false;"
"    btn.innerHTML = '<span>🔄</span> Atualizar Redes';"
"  }"
"}"
"async function saveCredentials(e) {"
"  e.preventDefault();"
"  const ssid = manualMode ? document.getElementById('ssidManual').value.trim() : document.getElementById('ssidSelect').value.trim();"
"  const password = document.getElementById('password').value;"
"  const box = document.getElementById('statusBox');"
"  const btn = document.getElementById('submitBtn');"
"  if (!ssid) { alert('Por favor, selecione ou digite o nome da rede!'); return; }"
"  btn.disabled = true;"
"  box.className = 'status-info';"
"  box.style.display = 'block';"
"  box.innerHTML = 'Salvando credenciais e reiniciando a Web Radio...';"
"  try {"
"    const res = await fetch('/api/save', {"
"      method: 'POST',"
"      headers: { 'Content-Type': 'application/json' },"
"      body: JSON.stringify({ ssid, password })"
"    });"
"    if (res.ok) {"
"      box.className = 'status-success';"
"      box.innerHTML = '<b>Sucesso!</b> As credenciais foram gravadas na NVS.<br>A Web Radio está conectando à sua rede Wi-Fi.<br>Você já pode se reconectar à sua rede local!';"
"    } else {"
"      throw new Error('Falha ao salvar');"
"    }"
"  } catch (err) {"
"    box.className = 'status-info';"
"    box.innerHTML = 'Erro ao enviar dados. Verifique a conexão com 10.10.10.1.';"
"    btn.disabled = false;"
"  }"
"}"
"window.addEventListener('load', () => { scanNetworks(); });"
"</script>"
"</body>"
"</html>";

#endif // SETUP_PAGE_H
